/**
 * Do not edit this file manualy, it will be overwritten by Platypus Application Designer.
 */
if (!platypus) {
	var platypus = {};
}
platypus.ready = function() {
	require(['Статус_ключа'], function(){
		var f = new Статус_ключа();
		f.show();
	});
};
